from step_exec_lib.errors import Error


class GiantSwarmValidatorError(Error):
    pass
